### ISSUE TITLE
Set up team terminal output as grid

### ISSUE THREAD

**Issue by biggestcookie** [biggestcookie/Pokemon-py#4]
Currently the player's team is printed as a long line of text blocks representing each Pokemon. This is hard for the user to read on different screen sizes. Modify the output using Python's `curses` module and print this out as a 3 x 2 grid instead.

**Comment by biggestcookie** [comment]
Decided against `curses` and instead opted for Python's inbuilt string formatting.
Output:
```
Drapion joined your team!
No.  Name        Health  Type    Type 2  
#452 Drapion     49/49   Dark    Poison

**Comment by ghost** [comment]
The switch looks good. It is easy to read and follow for potential users!
